name: thaumato
channels:
  - nvidia/label/cuda-11.3.1
  - anaconda
  - defaults
dependencies:
  - pip=23.1
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=openblas
  - boltons=23.0.0=py310h06a4308_0
  - brotlipy=0.7.0=py310h7f8727e_1002
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.08.22=h06a4308_0
  - certifi=2023.7.22=py310h06a4308_0
  - cffi=1.15.1=py310h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - conda=23.3.1=py310h06a4308_0
  - conda-content-trust=0.1.3=py310h06a4308_0
  - conda-package-handling=2.0.2=py310h06a4308_0
  - conda-package-streaming=0.7.0=py310h06a4308_0
  - cryptography=39.0.1=py310h9ce1e76_0
  - cuda-command-line-tools=11.3.1=h712c49d_0
  - cuda-compiler=11.3.1=h712c49d_0
  - cuda-cudart=11.3.109=hfb95d0c_0
  - cuda-cuobjdump=11.3.122=hbf6ec6b_0
  - cuda-cupti=11.3.111=h12ad217_0
  - cuda-cuxxfilt=11.3.122=h4dc11a3_0
  - cuda-gdb=11.3.109=h33b7820_0
  - cuda-libraries=11.3.1=h712c49d_0
  - cuda-libraries-dev=11.3.1=h712c49d_0
  - cuda-memcheck=11.3.109=hf5cb439_0
  - cuda-nvcc=11.3.122=h4814707_0
  - cuda-nvdisasm=11.3.122=ha26faa6_0
  - cuda-nvml-dev=11.3.58=hc25e488_0
  - cuda-nvprof=11.3.111=h95a27d4_0
  - cuda-nvprune=11.3.122=hb3346b8_0
  - cuda-nvrtc=11.3.122=h1aa17d8_0
  - cuda-nvtx=11.3.109=h4ec7630_0
  - cuda-nvvp=11.3.111=h4c4416a_0
  - cuda-samples=11.3.58=h6d5b628_0
  - cuda-sanitizer-api=11.3.111=h2446cfc_0
  - cuda-thrust=11.3.109=he8b717c_0
  - cuda-toolkit=11.3.1=h712c49d_0
  - cuda-tools=11.3.1=h712c49d_0
  - cuda-visual-tools=11.3.1=h712c49d_0
  - cyrus-sasl=2.1.28=h9c0eb46_1
  - dbus=1.13.18=hb2f20db_0
  - expat=2.5.0=h6a678d5_0
  - fontconfig=2.14.1=h4c34cd2_2
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - glib=2.69.1=he621ea3_2
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - icu=58.2=he6710b0_3
  - idna=3.4=py310h06a4308_0
  - jpeg=9e=h5eee18b_1
  - jsonpatch=1.32=pyhd3eb1b0_0
  - jsonpointer=2.1=pyhd3eb1b0_0
  - krb5=1.20.1=h568e23c_1
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcublas=11.5.1.109=h0fd73e7_0
  - libcufft=10.4.2.109=h2344711_0
  - libcups=2.4.2=ha637b67_0
  - libcurand=10.2.4.109=h0189693_0
  - libcusolver=11.1.2.109=h1e009e5_0
  - libcusparse=11.6.0.109=hf5bfba9_0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20221030=h5eee18b_0
  - libevent=2.1.12=h8f2d780_0
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libllvm14=14.0.6=hdb19cb5_3
  - libnpp=11.3.3.95=h122bb27_0
  - libnvjpeg=11.5.0.109=h159916b_0
  - libopenblas=0.3.21=h043d6bf_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.15=h37d81fd_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.1=h6a678d5_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.3=hcbfbd50_0
  - libxslt=1.1.37=h2085143_0
  - lz4-c=1.9.4=h6a678d5_0
  - mysql=5.7.24=he378463_2
  - ncurses=6.4=h6a678d5_0
  - nomkl=3.0=0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - openblas-devel=0.3.21=h06a4308_0
  - openssl=1.1.1w=h7f8727e_0
  - packaging=23.0=py310h06a4308_0
  - pcre=8.45=h295c915_0
  - pluggy=1.0.0=py310h06a4308_1
  - ply=3.11=py310h06a4308_0
  - pycosat=0.6.4=py310h5eee18b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.0.0=py310h06a4308_0
  - pyqt=5.15.7=py310h6a678d5_1
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.9=h7a1cb2a_0
  - qt-main=5.15.2=h5b8104b_9
  - qt-webengine=5.15.9=h9ab4d14_7
  - qtwebkit=5.212=h3fafdc1_5
  - readline=8.2=h5eee18b_0
  - requests=2.28.1=py310h06a4308_1
  - ruamel.yaml=0.17.21=py310h5eee18b_0
  - ruamel.yaml.clib=0.2.6=py310h5eee18b_1
  - setuptools=65.6.3=py310h06a4308_0
  - sip=6.6.2=py310h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - toolz=0.12.0=py310h06a4308_0
  - tqdm=4.65.0=py310h2f386ee_0
  - urllib3=1.26.15=py310h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.10=h5eee18b_1
  - zlib=1.2.13=h5eee18b_0
  - zstandard=0.19.0=py310h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      # - cython<3.0.0
      # - pyyaml==5.4.1
      - absl-py==1.4.0
      - addict==2.4.0
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - albumentations==1.2.1
      - antlr4-python3-runtime==4.8
      - anyio==3.6.2
      - appdirs==1.4.4
      - asttokens==2.2.1
      - async-timeout==4.0.2
      - attrs==23.1.0
      - backcall==0.2.0
      - black==21.4b2
      - cachetools==5.3.0
      - click==8.1.3
      - cloudpickle==2.1.0
      - comm==0.1.3
      - configargparse==1.5.3
      - contourpy==1.0.7
      - cycler==0.11.0
      - dash==2.9.3
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - deap==1.4.1
      - debugpy==1.6.7
      - decorator==5.1.1
      - docker-pycreds==0.4.0
      - einops==0.7.0
      - executing==1.2.0
      - ezdxf==1.2.0
      - fastapi==0.95.1
      - fastjsonschema==2.16.3
      - fire==0.4.0
      - flake8==6.0.0
      - flask==2.2.3
      - fonttools==4.39.3
      - frozenlist==1.3.3
      - fsspec==2023.4.0
      - fvcore==0.1.5.post20220512
      - gitdb==4.0.10
      - gitpython==3.1.31
      - google-auth==2.17.3
      - google-auth-oauthlib==1.0.0
      - grpcio==1.54.0
      - h11==0.14.0
      - hdbscan==0.8.33
      - hydra-core==1.0.5
      - imagecodecs==2024.1.1
      - imageio==2.21.1
      - importlib-metadata==3.10.1
      - iopath==0.1.10
      - ipykernel==6.22.0
      - ipython==8.12.0
      - ipywidgets==8.0.6
      - itsdangerous==2.1.2
      - jedi==0.18.2
      - jinja2==3.1.2
      - joblib==1.2.0
      - jsonschema==4.17.3
      - jupyter-client==8.2.0
      - jupyter-core==5.3.0
      - jupyterlab-widgets==3.0.7
      - kiwisolver==1.4.4
      - lazy-loader==0.2
      - libigl==2.5.0
      - lightning-utilities==0.9.0 
      - llvmlite==0.40.1
      - loguru==0.6.0
      - markdown==3.4.3
      - markupsafe==2.1.2
      - matplotlib==3.7.1
      - matplotlib-inline==0.1.6
      - mccabe==0.7.0
      # - torch==1.12.1
      # - torch-scatter==2.1.1
      # - torchmetrics==0.11.4
      # - torchvision==0.13.1
      # - pytorch-lightning==1.7.2
      # - minkowskiengine==0.5.4
      - multidict==6.0.4
      - mypy-extensions==1.0.0
      - natsort==8.3.1
      - nbformat==5.7.0
      - nest-asyncio==1.5.6
      - networkx==3.1
      - ninja==1.10.2.3
      - numba==0.57.1
      - numpy==1.24.2
      - oauthlib==3.2.2
      - omegaconf==2.0.6
      - open3d==0.18.0
      - open3d-cpu==0.18.0
      # - opencv-python-headless==4.7.0.72
      - opencv-python==4.9.0.80
      - pandas==2.0.0
      - parso==0.8.3
      - pathspec==0.11.1
      - pathtools==0.1.2
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.5.0
      - pip==23.1
      - platformdirs==3.2.0
      - plotly==5.14.1
      - plyfile==0.7.4
      # - pointnet2==0.0.0
      - portalocker==2.7.0
      - prompt-toolkit==3.0.38
      - protobuf==4.22.3
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycocotools==2.0.7
      - pycodestyle==2.10.0
      - pydantic==1.10.7
      - pydeprecate==0.3.2
      - pyflakes==3.0.1
      - pygments==2.15.1
      - pyparsing==3.0.9
      - pyqt5==5.15.10
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.13.0
      - pyqt6-qt6==6.5.2
      - pyqt6-sip==13.5.2
      - pyquaternion==0.9.9
      - pyrsistent==0.19.3
      - python-dateutil==2.8.2
      - python-dotenv==0.20.0
      - python-multipart==0.0.6
      - pytz==2023.3
      - pyviz3d==0.2.28
      - pywavelets==1.4.1
      - pyzmq==25.0.2
      - qudida==0.0.4
      - regex==2023.3.23
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scikit-image==0.20.0
      - scikit-learn==1.1.2
      - scipy==1.9.0
      - sentry-sdk==1.20.0
      - setproctitle==1.3.2
      - smmap==5.0.0
      - sniffio==1.3.0
      - stack-data==0.6.2
      - starlette==0.26.1
      - tabulate==0.9.0
      - tenacity==8.2.2
      - tensorboard==2.12.2
      - tensorboard-data-server==0.7.0
      - tensorboard-plugin-wit==1.8.1
      - termcolor==2.2.0
      - threadpoolctl==3.1.0
      - tifffile==2023.4.12
      - tornado==6.3
      - traitlets==5.9.0
      - trimesh==3.14.0
      - typing-extensions==4.6.0
      - tzdata==2023.3
      - uvicorn==0.21.1
      - volumentations==0.1.8
      - wandb==0.15.0
      - wcwidth==0.2.6
      - werkzeug==2.2.3
      - widgetsnbextension==4.0.7
      - yacs==0.1.8
      - yarl==1.8.2
      - zarr==2.17.1
      - zipp==3.15.0
prefix: /home/julian/anaconda3/envs/thaumato
